[workspace]

members = [
    "rlox_compiler", 
    "rlox_source", 
    "rlox_errors",
    "rlox_parser", 
    "rlox_ast", 
    "rlox_graphviz", 
    "rlox_interpreter",
    "rlox_cf_graph",
    "rlox_infra",
]
resolver = "2"

[workspace.dependencies]
test-case = "3.3.1"