version = "Two"
use_small_heuristics = "Off"

normalize_comments = true

max_width = 120
comment_width = 120

fn_params_layout = "Vertical"
struct_lit_width = 0
single_line_let_else_max_width = 0
single_line_if_else_max_width = 0
struct_variant_width = 0